### ISSUE TITLE
Review layers/X for libnetfilter_log

### ISSUE THREAD

**Issue by geaaru** [mocaccinoOS/issue-tracker#16]
```yaml
$ cat definition.yaml 
name: libnetfilter_log
version: 1.0.1
category: net-libs
requires:
- name: X
  version: '>=0'
  category: layers
labels:
  emerge.packages: net-libs/libnetfilter_log
  original.package.name: net-libs/libnetfilter_log
  original.package.version: 1.0.1
```

Probably we need to move some deps to another layer or as single packages.
